{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeclaw.fullname" . }}-secret
  labels:
    {{- include "kubeclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.gateway.token | quote }}
{{- end }}
